
package com.unileste.projetofinal.gui;
public class ContaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContaPanel
     */
    public ContaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTituloConta = new javax.swing.JLabel();
        jTituloNumeroConta = new javax.swing.JLabel();
        jTituloTipoConta = new javax.swing.JLabel();
        jTituloSaldo = new javax.swing.JLabel();
        jTituloCPFCliente = new javax.swing.JLabel();
        jComboBoxTipoDeConta = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTxtSaldo = new javax.swing.JTextField();
        jTxtCPFdoCliente = new javax.swing.JTextField();
        jButtonCriarConta = new javax.swing.JButton();
        jButtonBuscarConta = new javax.swing.JButton();
        jButtonExcluirConta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaDeContasCadastradas = new javax.swing.JTable();
        jTituloDaTabelaDeContasCadastradas = new javax.swing.JLabel();

        jTituloConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTituloConta.setText("Conta");

        jTituloNumeroConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTituloNumeroConta.setText("Número da conta: ");

        jTituloTipoConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTituloTipoConta.setText("Tipo de conta:");

        jTituloSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTituloSaldo.setText("Saldo R$:");

        jTituloCPFCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTituloCPFCliente.setText("CPF cliente:");

        jComboBoxTipoDeConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Poupança" }));
        jComboBoxTipoDeConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeContaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTxtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSaldoActionPerformed(evt);
            }
        });

        jButtonCriarConta.setText("Criar Conta");
        jButtonCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarContaActionPerformed(evt);
            }
        });

        jButtonBuscarConta.setText("Buscar Conta");

        jButtonExcluirConta.setText("Excluir");

        jTabelaDeContasCadastradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Conta 1", "Conta 2", "Conta  3"
            }
        ));
        jScrollPane2.setViewportView(jTabelaDeContasCadastradas);

        jTituloDaTabelaDeContasCadastradas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTituloDaTabelaDeContasCadastradas.setText("Tabela de contas cadastradas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jTituloConta))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTituloNumeroConta)
                .addGap(64, 64, 64)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTituloTipoConta)
                .addGap(126, 126, 126)
                .addComponent(jComboBoxTipoDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonCriarConta)
                .addGap(133, 133, 133)
                .addComponent(jButtonBuscarConta)
                .addGap(137, 137, 137)
                .addComponent(jButtonExcluirConta))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jTituloDaTabelaDeContasCadastradas))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTituloCPFCliente)
                    .addComponent(jTituloSaldo))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCPFdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTituloConta)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTituloNumeroConta))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTituloTipoConta))
                    .addComponent(jComboBoxTipoDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTituloSaldo)
                    .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTituloCPFCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTxtCPFdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCriarConta)
                    .addComponent(jButtonBuscarConta)
                    .addComponent(jButtonExcluirConta))
                .addGap(6, 6, 6)
                .addComponent(jTituloDaTabelaDeContasCadastradas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoDeContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeContaActionPerformed
       
    }//GEN-LAST:event_jComboBoxTipoDeContaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarContaActionPerformed
        
    }//GEN-LAST:event_jButtonCriarContaActionPerformed

    private void jTxtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSaldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarConta;
    private javax.swing.JButton jButtonCriarConta;
    private javax.swing.JButton jButtonExcluirConta;
    private javax.swing.JComboBox<String> jComboBoxTipoDeConta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaDeContasCadastradas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jTituloCPFCliente;
    private javax.swing.JLabel jTituloConta;
    private javax.swing.JLabel jTituloDaTabelaDeContasCadastradas;
    private javax.swing.JLabel jTituloNumeroConta;
    private javax.swing.JLabel jTituloSaldo;
    private javax.swing.JLabel jTituloTipoConta;
    private javax.swing.JTextField jTxtCPFdoCliente;
    private javax.swing.JTextField jTxtSaldo;
    // End of variables declaration//GEN-END:variables
}
